### ISSUE TITLE
potential license violation in the sample-recoder.py

### ISSUE THREAD

**Issue by Thompson-cyber** [omarzanji/ditto_activation#5]
Hi ,I found a potential issue regarding license violation in the [ditto_activation](https://github.com/omarzanji/ditto_activation) . The [sample-recorder.py](https://github.com/omarzanji/ditto_activation/blob/main/sample-recorder.py) generated by ChatGPT may have been derived from another repository, leading to a violation of its license terms. Below are the details:
### Details
The code [sample-recorder.py](https://github.com/omarzanji/ditto_activation/blob/main/sample-recorder.py)  appears to have been generated by ChatGPT with [```Generated by GPT with prompt: ...```](https://github.com/omarzanji/ditto_activation/blob/main/sample-recorder.py#L2C1-L2C31) comments.

However, the code from lines  15  to 50 seems to be a code clone with [PaddlePaddle/PaddleSpeech](https://github.com/PaddlePaddle/PaddleSpeech/) repository and [record.py](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/s2t/exps/deepspeech2/bin/deploy/record.py#L24) file. The main difference between the two code snippets is the variable name and values. Additionally, the ChatGPT generated code was updated on **Mar/31/2023** and the cloned code was updated on **Nov/3/2021**.

https://github.com/omarzanji/ditto_activation/blob/29dd6d17572072c793448b0c557728d749094e87/sample-recorder.py#L13-L50

There is no license for the ChatGPT-generated code in  sample-recorder.py and the repository. However, the cloned code is under [Apache-2.0](https://github.com/PaddlePaddle/PaddleSpeech?tab=Apache-2.0-1-ov-file#readme) license.
According to the conditions of this [Apache-2.0](https://github.com/PaddlePaddle/PaddleSpeech?tab=Apache-2.0-1-ov-file#readme) license :
>You must give any other recipients of the Work or  Derivative Works a copy of this License;

Due to the ChatGPT-generated code having no license and the cloned code being under the  [[Apache-2.0](https://github.com/PaddlePaddle/PaddleSpeech?tab=Apache-2.0-1-ov-file#readme)](https://github.com/PaddlePaddle/PaddleSpeech?tab=Apache-2.0-1-ov-file#readme)  license, there may be a potential license violation. 

1. How do you view potential license conflicts between ChatGPT-generated code and existing open-source code?
2. Is there a potential license conflict between the  [sample-recorder.py](https://github.com/omarzanji/ditto_activation/blob/main/sample-recorder.py) and the   [record.py](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/s2t/exps/deepspeech2/bin/deploy/record.py#L24) ?
3. If the license violation exists, would you add some explanation about the open-source licenses at the file level or repository level?

**Comment by Thompson-cyber** [comment]
Hi, I would be very grateful for any updates or feedback you can give when you get a moment. 😊

**Comment by omarzanji** [comment]
Hello, I have changed the license from Apache to MIT, where now the code is not required to have the license. If you want me to change the code, I can do this too as the lines that were generated from GPT that copied a snippet of your code were quite rudimentary. Please let me know how you would like me to move forward.

**Comment by omarzanji** [comment]
Upon further inspection, `sample_recorder.py` is not  used for any main logic. It was generated as a test script to collect activation samples. I have deleted the code in that file. Hope this resolved your issue!

**Comment by Thompson-cyber** [comment]
Thank for your reply! 😊
